// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/digitalocean/godo (interfaces: RegistriesService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks.go -package docr github.com/digitalocean/godo RegistriesService
//

// Package docr is a generated GoMock package.
package docr

import (
	context "context"
	reflect "reflect"

	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistriesService is a mock of RegistriesService interface.
type MockRegistriesService struct {
	ctrl     *gomock.Controller
	recorder *MockRegistriesServiceMockRecorder
}

// MockRegistriesServiceMockRecorder is the mock recorder for MockRegistriesService.
type MockRegistriesServiceMockRecorder struct {
	mock *MockRegistriesService
}

// NewMockRegistriesService creates a new mock instance.
func NewMockRegistriesService(ctrl *gomock.Controller) *MockRegistriesService {
	mock := &MockRegistriesService{ctrl: ctrl}
	mock.recorder = &MockRegistriesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistriesService) EXPECT() *MockRegistriesServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRegistriesService) Create(arg0 context.Context, arg1 *godo.RegistryCreateRequest) (*godo.Registry, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*godo.Registry)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockRegistriesServiceMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRegistriesService)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockRegistriesService) Delete(arg0 context.Context, arg1 string) (*godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*godo.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRegistriesServiceMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRegistriesService)(nil).Delete), arg0, arg1)
}

// DeleteManifest mocks base method.
func (m *MockRegistriesService) DeleteManifest(arg0 context.Context, arg1, arg2, arg3 string) (*godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteManifest", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*godo.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteManifest indicates an expected call of DeleteManifest.
func (mr *MockRegistriesServiceMockRecorder) DeleteManifest(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteManifest", reflect.TypeOf((*MockRegistriesService)(nil).DeleteManifest), arg0, arg1, arg2, arg3)
}

// DeleteTag mocks base method.
func (m *MockRegistriesService) DeleteTag(arg0 context.Context, arg1, arg2, arg3 string) (*godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTag", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*godo.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTag indicates an expected call of DeleteTag.
func (mr *MockRegistriesServiceMockRecorder) DeleteTag(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTag", reflect.TypeOf((*MockRegistriesService)(nil).DeleteTag), arg0, arg1, arg2, arg3)
}

// DockerCredentials mocks base method.
func (m *MockRegistriesService) DockerCredentials(arg0 context.Context, arg1 string, arg2 *godo.RegistryDockerCredentialsRequest) (*godo.DockerCredentials, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DockerCredentials", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.DockerCredentials)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DockerCredentials indicates an expected call of DockerCredentials.
func (mr *MockRegistriesServiceMockRecorder) DockerCredentials(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DockerCredentials", reflect.TypeOf((*MockRegistriesService)(nil).DockerCredentials), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockRegistriesService) Get(arg0 context.Context, arg1 string) (*godo.Registry, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*godo.Registry)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockRegistriesServiceMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRegistriesService)(nil).Get), arg0, arg1)
}

// GetGarbageCollection mocks base method.
func (m *MockRegistriesService) GetGarbageCollection(arg0 context.Context, arg1 string) (*godo.GarbageCollection, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGarbageCollection", arg0, arg1)
	ret0, _ := ret[0].(*godo.GarbageCollection)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetGarbageCollection indicates an expected call of GetGarbageCollection.
func (mr *MockRegistriesServiceMockRecorder) GetGarbageCollection(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGarbageCollection", reflect.TypeOf((*MockRegistriesService)(nil).GetGarbageCollection), arg0, arg1)
}

// GetOptions mocks base method.
func (m *MockRegistriesService) GetOptions(arg0 context.Context) (*godo.RegistryOptions, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptions", arg0)
	ret0, _ := ret[0].(*godo.RegistryOptions)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOptions indicates an expected call of GetOptions.
func (mr *MockRegistriesServiceMockRecorder) GetOptions(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptions", reflect.TypeOf((*MockRegistriesService)(nil).GetOptions), arg0)
}

// GetSubscription mocks base method.
func (m *MockRegistriesService) GetSubscription(arg0 context.Context) (*godo.RegistrySubscription, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscription", arg0)
	ret0, _ := ret[0].(*godo.RegistrySubscription)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockRegistriesServiceMockRecorder) GetSubscription(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscription", reflect.TypeOf((*MockRegistriesService)(nil).GetSubscription), arg0)
}

// List mocks base method.
func (m *MockRegistriesService) List(arg0 context.Context) ([]*godo.Registry, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]*godo.Registry)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRegistriesServiceMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRegistriesService)(nil).List), arg0)
}

// ListGarbageCollections mocks base method.
func (m *MockRegistriesService) ListGarbageCollections(arg0 context.Context, arg1 string, arg2 *godo.ListOptions) ([]*godo.GarbageCollection, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGarbageCollections", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*godo.GarbageCollection)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGarbageCollections indicates an expected call of ListGarbageCollections.
func (mr *MockRegistriesServiceMockRecorder) ListGarbageCollections(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGarbageCollections", reflect.TypeOf((*MockRegistriesService)(nil).ListGarbageCollections), arg0, arg1, arg2)
}

// ListRepositoriesV2 mocks base method.
func (m *MockRegistriesService) ListRepositoriesV2(arg0 context.Context, arg1 string, arg2 *godo.TokenListOptions) ([]*godo.RepositoryV2, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepositoriesV2", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*godo.RepositoryV2)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRepositoriesV2 indicates an expected call of ListRepositoriesV2.
func (mr *MockRegistriesServiceMockRecorder) ListRepositoriesV2(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepositoriesV2", reflect.TypeOf((*MockRegistriesService)(nil).ListRepositoriesV2), arg0, arg1, arg2)
}

// ListRepositoryManifests mocks base method.
func (m *MockRegistriesService) ListRepositoryManifests(arg0 context.Context, arg1, arg2 string, arg3 *godo.ListOptions) ([]*godo.RepositoryManifest, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepositoryManifests", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*godo.RepositoryManifest)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRepositoryManifests indicates an expected call of ListRepositoryManifests.
func (mr *MockRegistriesServiceMockRecorder) ListRepositoryManifests(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepositoryManifests", reflect.TypeOf((*MockRegistriesService)(nil).ListRepositoryManifests), arg0, arg1, arg2, arg3)
}

// ListRepositoryTags mocks base method.
func (m *MockRegistriesService) ListRepositoryTags(arg0 context.Context, arg1, arg2 string, arg3 *godo.ListOptions) ([]*godo.RepositoryTag, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepositoryTags", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*godo.RepositoryTag)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRepositoryTags indicates an expected call of ListRepositoryTags.
func (mr *MockRegistriesServiceMockRecorder) ListRepositoryTags(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepositoryTags", reflect.TypeOf((*MockRegistriesService)(nil).ListRepositoryTags), arg0, arg1, arg2, arg3)
}

// StartGarbageCollection mocks base method.
func (m *MockRegistriesService) StartGarbageCollection(arg0 context.Context, arg1 string, arg2 ...*godo.StartGarbageCollectionRequest) (*godo.GarbageCollection, *godo.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartGarbageCollection", varargs...)
	ret0, _ := ret[0].(*godo.GarbageCollection)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StartGarbageCollection indicates an expected call of StartGarbageCollection.
func (mr *MockRegistriesServiceMockRecorder) StartGarbageCollection(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartGarbageCollection", reflect.TypeOf((*MockRegistriesService)(nil).StartGarbageCollection), varargs...)
}

// UpdateGarbageCollection mocks base method.
func (m *MockRegistriesService) UpdateGarbageCollection(arg0 context.Context, arg1, arg2 string, arg3 *godo.UpdateGarbageCollectionRequest) (*godo.GarbageCollection, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGarbageCollection", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*godo.GarbageCollection)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateGarbageCollection indicates an expected call of UpdateGarbageCollection.
func (mr *MockRegistriesServiceMockRecorder) UpdateGarbageCollection(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGarbageCollection", reflect.TypeOf((*MockRegistriesService)(nil).UpdateGarbageCollection), arg0, arg1, arg2, arg3)
}

// UpdateSubscription mocks base method.
func (m *MockRegistriesService) UpdateSubscription(arg0 context.Context, arg1 *godo.RegistrySubscriptionUpdateRequest) (*godo.RegistrySubscription, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscription", arg0, arg1)
	ret0, _ := ret[0].(*godo.RegistrySubscription)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateSubscription indicates an expected call of UpdateSubscription.
func (mr *MockRegistriesServiceMockRecorder) UpdateSubscription(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscription", reflect.TypeOf((*MockRegistriesService)(nil).UpdateSubscription), arg0, arg1)
}

// ValidateName mocks base method.
func (m *MockRegistriesService) ValidateName(arg0 context.Context, arg1 *godo.RegistryValidateNameRequest) (*godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateName", arg0, arg1)
	ret0, _ := ret[0].(*godo.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateName indicates an expected call of ValidateName.
func (mr *MockRegistriesServiceMockRecorder) ValidateName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateName", reflect.TypeOf((*MockRegistriesService)(nil).ValidateName), arg0, arg1)
}
