---
name: CI Platform Test (Windows)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.1"

      - name: Set up Goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - name: Install Linters
        run: |
          go install github.com/mgechev/revive@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build Windows Binary
        run: make build-snapshot

      - name: Run MCP Binary and Check Output
        shell: pwsh
        env:
          DIGITALOCEAN_API_TOKEN: test-key
        run: |
          $binary = Get-ChildItem -Path dist -Filter "mcp-digitalocean*.exe" -Recurse | Select-Object -First 1
          if (-not $binary) {
            Write-Error "Binary not found in dist directory."
            exit 1
          }
          $output = & $binary.FullName --log-level debug --digitalocean-api test-key 2>&1
          Write-Host $output
          if ($output -notmatch 'starting MCP server') {
            Write-Error 'Did not find "starting MCP server" in output.'
            exit 1
          }
